DROP TABLE IF EXISTS shops;

CREATE TABLE shops (
id int(6) NOT NULL AUTO_INCREMENT,
name varchar(60) NOT NULL,
employees_number int(6) NOT NULL,
PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS users
CREATE TABLE users (
id int(6) NOT NULL AUTO_INCREMENT,
USER_NAME varchar(60) NOT NULL UNIQUE,
password varchar(16),
TOKEN varchar(16),
ACCESS_DATE varchar(16),
PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;
